### ISSUE TITLE
Make the plugin compatible with Pipelines

### ISSUE THREAD

**Issue by alexanderlz** [alexanderlz/jenkins-pagerduty-plugin#18]
https://issues.jenkins-ci.org/browse/JENKINS-35353

**Comment by sebawo** [comment]
hi @alexanderlz!
When r u planning to add this feature to the plugin ?

**Comment by alexanderlz** [comment]
Hi @sebawo ,
Will try to add it during one of the following weekends

**Comment by sebawo** [comment]
Thanks a lot!

**Comment by Constantin07** [comment]
+1 Is there any way to use programmatically PagerDuty plugin from scripted Pipeline now (Groovy)?

**Comment by sebawo** [comment]
@alexanderlz  any update on this? Can you provide any ETA?

**Comment by sebawo** [comment]
@alexanderlz  ping :)

**Comment by alexanderlz** [comment]
@sebawo - yep, I didn't forget, let's use [gitter](https://gitter.im/jenkinsci/pagerduty-plugin) for conversations

**Comment by alexanderlz** [comment]
https://github.com/jenkinsci/pagerduty-plugin/releases/tag/pagerduty-0.3.0

should make its way to the update center in the next couple of hours
