### ISSUE TITLE
Customising description with environment variables

### ISSUE THREAD

**Issue by heskyji** [alexanderlz/jenkins-pagerduty-plugin#2]
Hi Alex,

First of all thanks very much for the great plugin.

Would it possible to add support of customising description with environment variables? 

Thanks!

**Comment by alexanderlz** [comment]
Hi @heskymatic ,

You want it to pass the description from other job?
Provide me with example of how would you like to use it - and I will implement :smile:

**Comment by heskyji** [comment]
Hi @alexanderlz

Not from other job. 

Just use the Environment Variables of the currrent job. 

Here is a list of the available Environment Variables:
https://wiki.jenkins-ci.org/display/JENKINS/Building+a+software+project#Buildingasoftwareproject-JenkinsSetEnvironmentVariables
But I think the list is incomplete though. 

Thanks!

**Comment by alexanderlz** [comment]
Hi @heskymatic ,

Thanks for opening the issue,
the modified plugin is available here 
https://github.com/alexanderlz/jenkins-pagerduty-plugin/tree/v0.2.1

**Comment by heskyji** [comment]
@alexanderlz Great! Looking forward to using it soon! Thanks!

**Comment by heskyji** [comment]
Hi @alexanderlz when will the new release be available on https://wiki.jenkins-ci.org/display/JENKINS/PagerDuty+Plugin ?

**Comment by alexanderlz** [comment]
@heskymatic  - yes, will upload it there today
