### ISSUE TITLE
Migrate to Pagerduty v2 API

### ISSUE THREAD

**Issue by najboljsi007** [alexanderlz/jenkins-pagerduty-plugin#20]
I don't know exactly, how this plugin works, but if you are using PD API v1, please migrate to PD v2 API, because they will shut it down on 6 of July 2017.

FAQ:
https://v2.developer.pagerduty.com/docs/api-v2-frequently-asked-questions

How to migrate:
https://v2.developer.pagerduty.com/docs/migrating-to-api-v2

**Comment by najboljsi007** [comment]
@alexanderlz any updates?

**Comment by alexanderlz** [comment]
@najboljsi007 - yes, actually the new version is ready, I didn't release it to update center yet, want to give it a bit more testing.
want to participate in testing the new plugin version?
there is a channel I created on [gitter](https://gitter.im/jenkinsci/pagerduty-plugin), feel free to join and ping me there
