### ISSUE TITLE
Please add option for description in PD plugin

### ISSUE THREAD

**Issue by podbregarb** [alexanderlz/jenkins-pagerduty-plugin#25]
I saw this:
"Alex Gray
I created a PR for adding details myself, here: https://github.com/jenkinsci/pagerduty-plugin/pull/3

It's been working fine for me.  If you can merge that bad boy in (or comment on any issues you see with the code, let me know, I'll try to fix it up ASAP) :)"

It would be so useful for us. Please add it.

**Comment by alexanderlz** [comment]
it's already merged, which version of PD plugin are you using?

come to gitter chat https://gitter.im/jenkinsci/pagerduty-plugin

**Comment by podbregarb** [comment]
Oh, sorry, I didn't notice it's already merged because of date of latest release (it says 2017, but it's 2018). Closing issue.
