### ISSUE TITLE
Incident key deleted after Jenkins restart

### ISSUE THREAD

**Issue by podbregarb** [alexanderlz/jenkins-pagerduty-plugin#26]
A job fails and PD incident is triggered. On Jenkins restart, incident key disappears and when job goes back to normal, incident doesn't resolve.
Can anything be done about this?

**Comment by alexanderlz** [comment]
yes, will implement persisting incidents.
thanks!

**Comment by podbregarb** [comment]
Anything new on this issue?

**Comment by alexanderlz** [comment]
yes (sorry for the delay).
on monday 28/05/18 I'll give you an *.hpi to test.
if it solves the issue - I'll upload it to the plugin-center.
