### ISSUE TITLE
please add a event_class: "deploy"

### ISSUE THREAD

**Issue by jcalcada** [alexanderlz/jenkins-pagerduty-plugin#29]
Hi folks - whoever created this plugin - thanks! it's great.   Just one quick enhancement request.   If you could please add into your payload event_class: "deploy" that would be great.   That will let pagerduty know that it should display a diamond (indicating a build/deploy) instead of a standard event.

**Comment by alexanderlz** [comment]
Hi @jcalcada ,
Thanks for the comment, I'm can you point me to the point in PD documentation about the event_class?
I was looking here:
https://v2.developer.pagerduty.com/docs/send-an-event-events-api-v2
but I don't see anything related to it.

**Comment by jcalcada** [comment]
Hi @alexanderlz, 

Thanks for the quick reply.  There is some documentation here: https://support.pagerduty.com/docs/visibility-console.  The bottom of the article you'll notice in the sample script a  "event_class: tweet" (which populates the visibiliity console with a "T").     There is also a event_class: "deploy" but they don't give an example of that so I will ask support to add that.     If you could possibly provide a radio button in the plugin like "Set to "Deploy"  then that will allow folks to see the diamond shape in the visibility console indicating a deployment.    I can test it for you and show you the results if you could do that.  Really appreciate it.

**Comment by alexanderlz** [comment]
Hi @jcalcada 
Can you send me the list of event_classes that you can see as supported?
I'll create you something for test

**Comment by jcalcada** [comment]
Not sure if you notice in the diagram but there are essentially only two new classes that I am aware of.   One is “twitter” as shown in the doc,  and the other is “deploy” which is represented as a diamond.  There may be more coming down the line but as you can imagine your plugin with a “deploy” would provide great value because an SRE/LoB can clearly see a deploy occurred and then it must have been a problem deploy because a huge number of events came in.   Then people on Twitter started to complain.   That was the intent of the new classes I guess.    So we can visually see the cause/effect.    

So for now I would just do the “deploy” (I think “twitter" would be irrelevant for the Jenkins plugin) 

Thanks for your help in this.

**Comment by alexanderlz** [comment]
can you also send me a screenshot of where can I see the diamond, or even better - tell me where in pagerduty admin console?
cause I added the event_class in my test, but wasn't able to spot anything different in PD ui, (checked visibility tab too)

you can also use the gitter.im chat for more chat like communication 

[here](https://gitter.im/jenkinsci/pagerduty-plugin?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by jcalcada** [comment]
Hi Alexander - here is a screen shot. I notice that you use the square utility and in the code you might want to try and change line 22 in the event.java module to "deploy".   I'm not a great coder so I may be totally off track but you can give it a try.   If it doesn't work no worries,  I will use the "CUSTOM EVENT TRANSFORMER" which is a pagerduty utility and is shown the image popup below. 

https://github.com/square/pagerduty-incidents/blob/master/src/main/java/com/squareup/pagerduty/incidents/Event.java


![image](https://user-images.githubusercontent.com/23078419/47270495-9c2fd500-d53a-11e8-9db7-a8737a8f10df.png)

**Comment by jcalcada** [comment]
Hi Alexander - I'm going to close this since its not something you should change on your side.   I was able to get the DIAMOND shape using the PD "Custom Event Transformer" to take your event info and just change the  class event to deploy.  All works great now.  Thanks for your time and attempt.
