### ISSUE TITLE
New parameters in PagerDutyTrigger.java break existing pipelines

### ISSUE THREAD

**Issue by mhutchison89** [alexanderlz/jenkins-pagerduty-plugin#43]
Hello,

We recently ran an upgrade of the PagerDuty plugin directly from the Jenkins UI.  We're on the latest LTS 2.263.1 release.

I've noticed in the most recent release the parameters for the PagerDutyTrigger class have all changed names and there's been some additions there.  This no longer matches the Pipeline examples in the README for the repo anymore where parameters like 'incDetails' and 'incDescription' no longer exist.

I think anybody using these functions in their pipelines who upgrades will run into errors similar to the one below unless instructed to update their Jenkinsfiles.  I'm sure this is probably related to upstream changes with PagerDuty but it may warrant a note in the Jenkins link for the plugin or in the README.  Just a heads up.

`WARNING: Unknown parameter(s) found for class type 'org.jenkinsci.plugins.pagerduty.pipeline.PagerDutyTriggerStep': incDescription,incDetails,serviceKey
Triggering pagerDuty with routingKey null`

**Comment by alexanderlz** [comment]
Thanks for bringing it up,
will fix the docs later on today!

**Comment by alexanderlz** [comment]
documentation updated in 0.6.2
