### ISSUE TITLE
"java.lang.IllegalStateException: No match found" error on upgrade to 0.6.2

### ISSUE THREAD

**Issue by rnhurt** [alexanderlz/jenkins-pagerduty-plugin#48]
First off, I would like to thank you for building this plugin.  We've been using it for about 6 months and it's worked wonderfully. 
 That is until the last update.  Now, all of our jobs that are configured to use the "PagerDuty Incident Trigger" post-build action have started failing with this error:

```
java.lang.IllegalStateException: No match found
  at java.util.regex.Matcher.group(Matcher.java:536)
  at org.jenkinsci.plugins.pagerduty.util.PagerDutyUtils.extractDedupKey(PagerDutyUtils.java:36)
  at org.jenkinsci.plugins.pagerduty.PagerDutyTrigger.perform(PagerDutyTrigger.java:215)
  at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
  at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:803)
  at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:752)
  at hudson.model.Build$BuildExecution.post2(Build.java:177)
  at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:697)
  at hudson.model.Run.execute(Run.java:1932)
  at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
  at hudson.model.ResourceController.execute(ResourceController.java:97)
  at hudson.model.Executor.run(Executor.java:429)
Build step 'PagerDuty Incident Trigger' marked build as failure
```

Steps to resolve the problem:
1. remove the PagerDuty action
2. save the Jenkins job
3. run the Jenkins job
4. add the PagerDuty action back
5. Done!

While this gets the job back up and running it doesn't seem like the correct way to proceed.  In fact, we only noticed the failure because someone was doing maintenance on Jenkins and noticed that some of our production jobs were "failing".

**Comment by akrapfl** [comment]
Any other jenkins version changes done in the process (other plugins or master version change)?  What version of the plugin did you upgrade from @rnhurt ?

**Comment by akrapfl** [comment]
I did upgrade a few minor dependency versions in the pom.xml with the PR that went into 0.6.2, but the code in that stacktrace shouldn't have changed.  I don't _THINK_ my PR caused this, but you never know.  I'm not familiar with the use case that requires that utility method, and on first glance, I can't reproduce it myself.  I'm willing to help, but I would be guessing at a code change at this point.

**Comment by rnhurt** [comment]
@akrapfl, we update the Jenkins plugins generally once a month.  I don't have the specifics but I'm guessing the problem started right around the time we did the update.  I don't know the previous version and I'm sorry I can't be of more help.  I just wanted to open the ticket to see if anyone else had the problem and to see if there might be some other cause.

**Comment by akrapfl** [comment]
Understood.  As I said, I can't reproduce it myself, and don't know the history of this chunk of code.  It wasn't changed, but doesn't mean I didn't break it.  Also probably good to know that you PROBABLY came from version 0.6.1 where it worked.

One further question.  What options do you have selected in the post-build task, and could you post a screenshot of the history of a job that's failed?  I tried to test it by alternate successful runs and aborts, but that worked fine.

**Comment by rnhurt** [comment]
Here are the options that are enabled in the job:
![image](https://user-images.githubusercontent.com/24466/105715813-0db21700-5eec-11eb-9875-dc02c4aaedec.png)

The job itself is a simple Bash script that runs every 5 minutes and hits our health_check endpoints 
```
Started by timer
Running as SYSTEM
Building remotely on HealthChecksWorker (health-checks) in workspace /var/lib/jenkins/health-checks-worker/workspace/health-check-production
[health-check-production] $ /bin/sh -xe /tmp/jenkins3832416034422640809.sh
+ /opt/shared/health-check.sh /opt/shared/url-lists/production-url-list.txt
<<SUCCESS>> Health Check on https://mywebsite.com has passed with a Status: 200
<<SUCCESS>> Health Check on https://mywebsite-2.com has passed with a Status: 200
<<SUCCESS>> Health Check on https://mywebsite-3.com has passed with a Status: 200
ERROR: Build step failed with exception
java.lang.IllegalStateException: No match found
  at java.util.regex.Matcher.group(Matcher.java:536)
  at org.jenkinsci.plugins.pagerduty.util.PagerDutyUtils.extractDedupKey(PagerDutyUtils.java:36)
  at org.jenkinsci.plugins.pagerduty.PagerDutyTrigger.perform(PagerDutyTrigger.java:215)
  at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
  at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:803)
  at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:752)
  at hudson.model.Build$BuildExecution.post2(Build.java:177)
  at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:697)
  at hudson.model.Run.execute(Run.java:1932)
  at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
  at hudson.model.ResourceController.execute(ResourceController.java:97)
  at hudson.model.Executor.run(Executor.java:429)
Build step 'PagerDuty Incident Trigger' marked build as failure
[Slack Notifications] found #427588 as previous completed, non-aborted build
Finished: FAILURE
```

I'm not sure what you mean by a screenshot of the history or how that might be valuable.  Since the job runs every 5 minutes I don't have the history of when it broke, but here's a screenshot of when I fixed it:
![image](https://user-images.githubusercontent.com/24466/105716692-2ff86480-5eed-11eb-8976-a3ba536fd818.png)

**Comment by akrapfl** [comment]
Yeah, that's what I was looking for was the history of job executions, but since it's running so frequently, if you've dropped history, that's probalby the problem.  Actually, that makes me wonder, if this can be reproduced simply by restricting the executions the job retains.  🤔

**Comment by akrapfl** [comment]
OK, so I CAN reproduce this.  From what I can tell, it's unrelated to the changes in 0.6.2.  First my steps to reproduce:

1.  Create a freestyle job
2. check `Discard old builds` and set ma # to keep to 2
3. add a shell step with something trivial like `sleep 10; exit 1`
4. add the pagerduty incident trigger defining all required fields, and check `Resolve BACK-TO-NORMAL` and `ABORTED`
5.  Run the job once and abort
6. run two more times allowing it to error (this should result in a page on the service, and then the aborted build deleted from the build history
7. edit the job.  Comment out exit 1 in the shell script, and DELETE THE DEDUP KEY
8. run one more time.  The resulting [successful] build produces the stacktrace described.

**Comment by akrapfl** [comment]
My contention is that something (possibly related to the plugin upgrade) is wiping the dedup key.  Once lost, it's using the fallback mechanism to look at old job executions for it, but the history doesn't go back far enough.  This looks to be consistent with @rnhurt 's steps which deleted the config to get the build back to normal.  

This is the first plugin I've worked with that updates config after a job execution.  I'm not sure how to handle that.  I still think the fix I would do is just let it return null if it doesn't find the dedup key in old logs.  I am thinking that's going to let your execution pass.  Worst thing that happens is that it can't resolve ONE incident, but moving forward I'd think you would be better off.
