### ISSUE TITLE
Potential Issue with latest update?

### ISSUE THREAD

**Issue by unagisan** [alexanderlz/jenkins-pagerduty-plugin#7]
Alexander,

Thank you for adding in the ability to create multiple PD serviceKeys! We did notice something rather odd and or different. We use DSLs (groovyScript) to generate our Jenkins jobs and the PD plug-in would work fine once generated. When we use the DSLs to generate the jobs now, the plug-in doesn't work. We receive:

```
...
Unbale to activate pagerduty module, check configuration!
Build step 'PagerDuty Incident Trigger' marked build as failure
Finished: FAILURE
```

*we noticed there is a type as well with "unbale" :)

It's not until we 'configure' the job and hit save (no changes) that it then begins to work. When diffing the job before and after the save we noticed that it now adds two new elements to the job XML which it seems to rely on (whereas before it didn't), as follows:

```
<pagerDuty class="com.squareup.pagerduty.incidents.PagerDuty$1">...</pagerDuty>
<resultProbe>...</resultProbe>
```

I've attached the snippets of the jobs for more detail. Please let me know if you have any questions.

Thank you!

[configOutputSample.zip](https://github.com/alexanderlz/jenkins-pagerduty-plugin/files/80431/configOutputSample.zip)

**Comment by alexanderlz** [comment]
Thanks for notifying!
Can you share the snippet of groovy code that generates the job?

**Comment by unagisan** [comment]
Thanks for the quick reply! I've gone ahead and attached our before and after groovy snippet
[groovySnippets.zip](https://github.com/alexanderlz/jenkins-pagerduty-plugin/files/80467/groovySnippets.zip)

**Comment by unagisan** [comment]
Hey Alexander, I was wondering if there has been any progress on this? Thank you :)

**Comment by alexanderlz** [comment]
Haven't had time to look at it yet, will try to free some over the next weekend.

**Comment by unagisan** [comment]
Hey Alexander,

Thank you for the update! :)

Although, I was reviewing
https://wiki.jenkins-ci.org/display/JENKINS/PagerDuty+Plugin and I don't
see a new version?

Best,

Jeff H.

**Comment by alexanderlz** [comment]
Hi @unagisan ,

It should get there in the next couple of hours
you can try it manually from the releases section [here](https://github.com/jenkinsci/pagerduty-plugin/releases/tag/pagerduty-0.2.3)

**Comment by unagisan** [comment]
Awesome, yea I had a feeling it was a submission/approval process before it
shows up. Thank you for the quick reply ! :)

**Comment by alexanderlz** [comment]
sure,
lmk how it goes after you update
