### ISSUE TITLE
Clearing Alert if build is successful

### ISSUE THREAD

**Issue by edsyoo** [alexanderlz/jenkins-pagerduty-plugin#8]
Would there be a possibility of clearing an alert if it is rebuilt (or a periodic build) that has a successful concurrent build (or at any time later)?

**Comment by alexanderlz** [comment]
yes, it was in my plans.

good to know it will be useful :+1:

**Comment by razitz** [comment]
+1

**Comment by alexanderlz** [comment]
@edsyoo @razitz - just pushed a new release, 
https://github.com/alexanderlz/jenkins-pagerduty-plugin/releases/tag/v0.2.4

will give it some "test-days" before pushing to the jenkins repository, feel free to install it, any
feedback appreciable

**Comment by alexanderlz** [comment]
@aramisbear - you also asked about this feature on jenkins website, right?

**Comment by brightball** [comment]
I did

**Comment by alexanderlz** [comment]
@aramisbear - feel free to grab the hpi from the release mentioned above, or wait couple of days till I propagate the change to jenkins plugin repository.
